### PR TITLE
Gets HLA working again with Java 21

### PR DESCRIPTION
**Pull request by jarrodgreene**
Due to a reliance on internal ClassLoader details, HLA support broke with the update to Java 21. This has now been replaced with a custom ClassLoader to add in the RTI dependencies.

Fixes: Disco-66, CNR-2299

### CODE REVIEW

**Comment by jarrodgreene** [comment]
I think swapping to use a custom ClassLoader is the expected avenue for adding things to be loaded dynamically. The hla spec jar needs to be updated for the RtiFactoryFactory implementation to work with Java 9+ runtimes.

**Comment by jarrodgreene** [comment]
Just realised the testCustomRprMapperRegistration is still failing, which is because the updated hla jar is only loaded via the Eclipse .classpath file - not in the ant build. The ant build uses some random build of Portico instead - which would require me to be able to actually build the latest version of Portico - which I can not. So resolving that might need to get raised as a separate issue

**Comment by michaelrfraser** [comment]
Have just had a check with @jarrodgreene re the updated ieee156116e jar file. The contents of this jar are mandated by the IEEE1516e spec, but the java implementation provided by SISO uses the ImageIO SPI to register providers for the RtiFactory and Encoding helper classes. 

In modern Java 21 rules about which classes can use the ImageIO SPI have been tightened, and because the HLA related classes aren't part of the ImageIO system, attempts to register HLA factory classes with them fail.

Jarrod has taken the HLA4 implementation (which addresses this particular issue) and has patched in the RtiFactory and Encoding helper classes. Will look to have this addreessed in Portico in the future so we can just steal if from there.

**Comment by timpokorny** [comment]
@jarrodgreene @michaelrfraser - No issue with a custom classloader (although I'd change the name to `DiscoClassLoader` just to make it super clear and easy to identify). 

Only potential issue I can see is the use of `Thread.currentThread().setContextClassLoader()`. This will only change things for the current thread, not at a system/application level won't it? That seems like it could be problematic. Is there no analog to the system classloader any more?

**Comment by jarrodgreene** [comment]
@timpokorny Yeah so this is the happy Java path - which is _probably_ fine? As long as that same thread is the only one poking the RTI's around, they'll have the same thread context classloader - even if they spawn their own threads. Problems would come up if a different thread tried to start the RTI's or something along those lines.

I've had a bit more of a poke around - and we could continue to do basically the same thing as before - with the same issues around relying on internal details. The system loader is just now an `AppClassLoader` which extends from `BuiltinClassLoader` - which has an `appendClassPath` method we can get via reflection. 

But since that is in a unopened module or whatever - anything using disco would need to add a VM arg `--add-opens java.base/jdk.internal.loader=ALL-UNNAMED`. And it seems that even if we were to modularise Disco we can't just add that to the module-info file because you have to own the module (jdk.internal.loader) to do that? That seems like it could be problematic - we can deal with it just running CNR in dev easily, but clients trying to use the sdk would then need to also add that VM arg - which if nothing else I imagine would raise some questions.

**Comment by jarrodgreene** [comment]
Further on that last point about adding `-add-opens` - you can add a Manifest parameter that does the same thing - but that only works when running that jar specifically: 
> These attributes are interpreted only in the main executable JAR file of an application, i.e., in the JAR file specified to the -jar option of the Java run-time launcher; they are ignored in all other JAR files.

**Comment by jarrodgreene** [comment]
Renamed `CustomClassLoader` to `DiscoClassLoader` as requested.

**Comment by timpokorny** [comment]
So in this brave new Java 21 world there is no way (as a library) to extend the application classpath at runtime (without enforcing onerous things on the main application developer). Thanks, modules.

I've tested this and I think it will be OK, so I am happy to approve and merge. 

@jarrodgreene Note that I've updated the implementation so that it is safe to call multiple times. In the previous implementation I'm 98% sure (as much as anyone ever is with class loaders) that each subsequent call would wipe out any previous call because the context classloader was replaced with a new DiscoClassLoader (whose classpath was extended only with the content of the current call) each time. A little bit of dupe in the code now, but should definately be multiple call safe.

**Pull request merged**
